function chooseRandomPrompt() {

    randomIndex = Math.floor(Math.random() * propmt_list.length)
    document.getElementById("main_prompt").innerHTML = propmt_list[randomIndex];
  }

 propmt_list = [
  "What was the most peaceful moment during the day?",
  "Describe something you learned today that you didn’t know before.",
  "Would you change any of the decisions you made today?",
  "How were your meals today? Do you feel nourished?",
  "What frightened you today?",
  "Who do you wish you had talked to today? How do they improve your life?",
  "Describe the moments of frustration you felt today. How would your day have changed if those moments were different?",
  "If you’d had another hour during the day, how would you have spent it?",
  "Did something (or someone) empower you today?",
  "Did you stop yourself from doing something you enjoy today? Why or why not?",
  "Reflect on how your body feels. Where are you storing your stress? What put it there?",
  "Who helped you the most today? Who did you help the most?",
  "Describe your day from another person’s perspective. Is it different from yours?",
  "If you were in charge, what would you forbid immediately?",
  "What needs to change in your job for you to feel fulfilled?",
  "Write about a hobby that you’d like to pick up.",
  "If you could relive any day of your life and change nothing, what day would you choose?",
  "How would you like your life to be different in a year? How would you like it to be the same?",
  "If you had to live in another country, where would you live?",
  "How could you change your life to become a hero to someone else?",
  "What was something you desperately wanted as a child? What do you desperately want now?",
  "If you could take any college course you wanted, what would you take?",
  "Describe your ideal weekend. What would it include? What wouldn’t it include?",
  "Rewrite a conversation you’ve had in the way you wish it had gone.",
  "What would you do if you found a puppy in the street?",
  "What would you do with a million dollars if you had to spend it in one hour?",
  "What would you do if you needed to change your career or major?",
  "What would you do if you could suddenly read minds?",
  "What would you do if you were locked out of your house?",
  "What would you do if your loved one were accused of a crime?",
  "What would you do if you were stranded on a desert island with someone you dislike?",
  "What would do if you lost all your possessions? What would you replace? What wouldn’t you replace?",
  "What would you do if you lost one of your senses? Which would be the most difficult one to lose?",
  "Write a note to a teacher who inspired you. How have you used their lessons in your current life?",
  "What would you say to a childhood bully if you could?",
  "Write a letter to your teenage self.",
  "Put yourself 20 years in the future. Write a letter to your future self with questions and predictions.",
  "Write a thank you letter to someone after they gave you a terrible gift.",
  "Craft a breakup letter to a bad habit.",
  "Think about your first crush or love. Write them the letter you wish you’d sent.",
  "Write a letter from someone else to you. What do you need to hear from them?",
  "Look at your last few text messages. Rewrite one of them into a longer letter as if you were in the eighteenth century.",
  "Write a letter to someone you’ve lost.",
  "What was your best age so far?",
  "Do you have a memory that should be happy, but instead makes you sad? What about the other way around?",
  "When is a time in your life that you felt successful?",
  "Think about your best friend in childhood. What did you like to do together?",
  "Write about a trip you took where something (or everything!) didn’t go according to plan.",
  "Think about a lesson your parents taught you either by doing something well or not doing it well.",
  "When in your life have you felt brave?",
  "What book made you fall in love with reading?",
  "How old were you when you first felt like an adult?",
  "Who do you trust most? Why?",
  "What are your strengths in relationships (kindness, empathy, etc.)?",
  "How do you draw strength from loved ones?",
  "What do you value most in relationships (trust, respect, sense of humor, etc.)?",
  "What three important things have you learned from previous relationships?",
  "What five traits do you value most in potential partners?",
  "How do you show compassion to others? How can you extend that same compassion to yourself?",
  "What are three things working well in your current relationship? What are three things that could be better?",
  "What boundaries could you set in your relationships to safeguard your own well-being?",
  "What do you most want your children (or future children) to learn from you?",
  "How can you better support and appreciate your loved ones?",
  "What does love mean to you? How do you recognize it in a relationship?",
  "List three things you’d like to tell a friend, family member, or partner.",
  "How do you use your personal strengths and abilities at work?",
  "How do your co-workers and supervisors recognize your strengths?",
  "How does work fulfill you? Does it leave you wanting more?",
  "What part of your workday do you most enjoy?",
  "What about your work feels real, necessary, or important to you?",
  "Do you see yourself in the same job in 10 years?",
  "What are your career ambitions?",
  "What three things can help you begin working to accomplish those goals?",
  "What can you do to improve your work performance?",
  "What does your work teach you? Does it offer continued opportunities for learning and growth?",
  "Does your work drain or overwhelm you? Why? Is this something you can change?",
  "What values do you consider most important in life (honesty, justice, altruism, loyalty, etc.)? How do your actions align with those values?",
  "What three changes can you make to live according to your personal values?",
  "Describe yourself using the first 10 words that come to mind. Then, list 10 words that you’d like to use to describe yourself. List a few ways to transform those descriptions into reality.",
  "What do you appreciate most about your personality? What aspects do you find harder to accept?",
  "Explore an opinion or two that you held in the past but have since questioned or changed. What led you to change that opinion?",
  "List three personal beliefs that you’re willing to reconsider or further explore.",
  "Finish this sentence: “My life would be incomplete without …”",
  "Describe one or two significant life events that helped shape you into who you are today.",
  "When do you trust yourself most? When do you find it harder to have faith in your instincts?",
  "What three things would you most like others (loved ones, potential friends and partners, professional acquaintances, etc.) to know about you?",
  "What difficult thoughts or emotions come up most frequently for you?",
  "Which emotions do you find hardest to accept (guilt, anger, disappointment, etc.)? How do you handle these emotions?",
  "Describe a choice you regret. What did you learn from it?",
  "What parts of daily life cause stress, frustration, or sadness? What can you do to change those experiences?",
  "What are three things that can instantly disrupt a good mood and bring you down? What strategies do you use to counter these effects?",
  "What are three self-defeating thoughts that show up in your self-talk? How can you reframe them to encourage yourself instead?",
  "What go-to coping strategies help you get through moments of emotional or physical pain?",
  "Who do you trust with your most painful and upsetting feelings? How can you connect with them when feeling low?",
  "What do you fear most? Have your fears changed throughout life?",
  "Describe your favorite thing to do when feeling low.",
  "What three ordinary things bring you the most joy?",
  "List three strategies that help you stay present in your daily routines. Then, list three strategies to help boost mindfulness in your life.",
  "How do you prioritize self-care?",
  "Describe two or three things you do to relax.",
  "What aspects of your life are you most grateful for?",
  "How do you show yourself kindness and compassion each day?",
  "Write a short love letter to some object or place that makes you happy.",
  "What place makes you feel most peaceful? Describe that place using all five senses.",
  "List 10 things that inspire or motivate you.",
  "What are your favorite hobbies? Why?",
  "What parts of life surprised you most? What turned out the way you expected it would?",
  "What three things would you share with your teenage self? What three questions would you want to ask an older version of yourself?",
  "List three important goals. How do they match up to your goals from 5 years ago?",
  "Do your goals truly reflect your desires? Or do they reflect what someone else (a parent, partner, friend, etc.) wants for you?",
  "What helps you stay focused and motivated when you feel discouraged?",
  "What do you look forward to most in the future?",
  "Identify one area where you’d like to improve. Then, list three specific actions you can take to create that change.",
  "How do you make time for yourself each day?",
  "What do you most want to accomplish in life?",
  "List three obstacles lying in the way of your contentment or happiness. Then, list two potential solutions to begin overcoming each obstacle.",
  "What are five things you appreciate about yourself?",
  "What are three great things that happened yesterday?",
  "What are 30 things that bring you joy?",
  "What are you looking forward to right now? If you can’t think of anything, what can you do to change that?",
  "What is one thing under $100 that has made your life easier?",
  "What are 10 things you’re actively enjoying about life right now?",
  "Write about the most fun you had recently. What were you doing and who with?",
  "Name the top three emotions you are feeling at the moment. What are the emotions you want to feel today?",
  "What is the one thing you would tell your teenage self if you could?",
  "What is your body craving at the moment?",
  "What are 10 questions you wish you had the answers to right now?",
  "What do you know to be true today that you didn’t know a year ago?",
  "What are you scared of right now?",
  "What’s not working in your life right now?",
  "Write someone a letter with whom you have an unresolved issue.",
  "Write about someone you miss, what do you miss about them? How do they make you feel?",
  "What would your ideal day look like? Where would you be, what would you be doing and who with?",
  "Describe your perfect home – where is it, what does it look like and who do you share it with?",
  "When you were younger, what did you want to be when you grew up and why?",
  "What do you need more of in your life?",
  "If failure wasn’t possible, what would you be doing right now?",
  "If you only had one year left of life, what would you do?",
  "In another life, who would you want to be? Write out this character, what they do for a living, their personality traits, etc.",
  "What’s something you wish others knew about you?",
  "Who is someone you admire? What qualities do you love about them?",
  "Who is someone you envy and why?",
  "What distracts you from what’s truly important each day?",
  "If you decided right now that you had enough money, and that you would always have enough, what would you do with your life?",
  "When you picture yourself 10 years from now, what do you want to have achieved and experienced?",
  "How do you want to contribute your talents and passions to the world? Who could be touched by you and how would it affect them?",
  "What are your plans for this weekend?",
  "Write 5 affirmations for when you are feeling low.",
  "What is the best book you have read recently?",
  "How have you grown this year?",
  "What are the most important life lessons you have learned?",
  "Having trouble sleeping? What’s keeping you up?",
  "What is the last dream you remember?",
  "Name the three biggest priorities in your life right now.",
  "What are your biggest fears?",
  "Do you have a fear that is stopping you from achieving your goals?",
  "Name three challenges…. and three ways to overcome them.",
  "Write down your ultimate way to relax.",
  "What would you do if you were granted three wishes?",
  "How about if you were given five wishes?",
  "Name three bad habits you would like to change.",
  "What was the last show you went to?",
  "Do you have a secret talent you are hiding?",
  "Add some more items to your bucket list…if you don’t have a bucket list, start one.",
  "What is your biggest regret?",
  "Think about someone you really love. Write about the person that came to mind.",
  "List the best 10 moments of your life so far.",
  "What 5 things are you grateful for this week?",
  "Name the one thing you are most grateful for in your life at this moment.",
  "Write about 5 amazing childhood memories you are grateful for.",
  "Which people in your life are you most grateful for.",
  "Write about something that made you smile today.",
  "When were you last surprised?",
  "What is the most exhilarating thing that has happened to you this year?",
  "Name a challenge you have overcome and how it helped you to grow.",
  "How can you show gratitude more?",
  "What are 3 things that have happened to you which were difficult but you are now grateful for the experience?",
  "Keep a food tracker for the day.",
  "Make a meal planner. Head to our meal planning post for ideas.",
  "Write down your measurements and weight so you can compare later.",
  "What is your favorite way to exercise?",
  "Did you make healthy choices today?",
  "Name one simple way you can take a step to be healthier.",
  "How can you make activity part of your normal routine?",
  "What is your favorite food?",
  "List your fitness and health goals.",
  "Are you feeling stressed?",
  "Keep a mood or habit tracker to help understand your mental health.",
  "Think about what triggers your stress, emotions, poor eating habits.",
  "What is a bad habit you would like to change? What actionable steps can you take to make it happen?",
  "What are your top 10 goals?",
  "Write down actionable steps to help you reach a goal.",
  "What is your 1-year goal?",
  "What is your 5-year goal?",
  "What is your 10-year goal?",
  "If you could start life again, would you? What would you change?",
  "Who is someone that inspires you and why?",
  "Is there a hobby you would like to start?",
  "Name a skill you would love to learn.",
  "What kind of person do you aspire to be?",
  "What is your favorite childhood memory?",
  "Write about the first memory you have.",
  "Describe your childhood.",
  "Do you have an embarrassing moment that still makes you cringe?",
  "Which was your best birthday ever and why?",
  "What was a hobby you loved as a kid?",
  "Write about your favorite memory with your parents.",
  "What was your favorite toy?",
  "What is your best memory with some of the special people in your life?",
  "What is a memory that always makes you smile?",
  "Where is the place you would like to visit the most?",
  "What has been your best trip so far?",
  "Who is the person you would like to travel with the most and why?",
  "If you could go back in time, where would you go?",
  "Describe your dream vacation.",
  "Write about a road trip you would love to take.",
  "How does seeing somewhere new make you feel?",
  "What is a food you would love to try from a different country?",
  "What is the worst vacation you have ever had/",
  "Name 10 places you would love to see.",
  "Write your day in bullet points.",
  "Do your current friendships and relationships bring joy to you?",
  "What is your biggest concern right now?",
  "Do you think you are a positive or negative person?",
  "What are your best qualities?",
  "Could you be a better friend?",
  "Could you be a better partner/wife/husband/mother/father/daughter or Son?",
  "Write about your top five personal strengths.",
  "What things change your mood from positive to negative?",
  "Make a list of 10 affirmations that will lift your mood.",
  "Do you have a morning routine? Can it be improved?",
  "How are you feeling today?",
  "What is something you want to achieve this year?",
  "Write five goals for January.",
  "Make plans for Spring.",
  "Have actionable steps for your big year goals.",
  "Do you have all the important dates and birthdays in your journal?",
  "Write how each season affects your mood and energy levels.",
  "Make a plan for your dream garden.",
  "What summer plans do you have?",
  "Write the perfect way to spend Easter.",
  "How would you make a raining day amazing?",
  "What is a challenge you would like to overcome?",
  "Plan all the holidays you celebrate.",
  "How are you progressing with your year goals?",
  "Name a fear you would like to overcome.",
  "What are you grateful for in your life?",
  "What have been the best summer vacations you have had?",
  "Write about your dream summer vacation.",
  "If you went back to school, what would you study?",
  "What are 10 affirmations you could say daily?",
  "What are you looking forward to in August?",
  "If you are a parent, plan an amazing day with your kid/s.",
  "What is your favorite thing about Fall?",
  "Write a poem about Fall",
  "Make plans for celebrating Halloween",
  "What was your all-time favorite Halloween costume?",
  "What food really puts you in the Fall mood?",
  "List some mood lifters for when the weather starts to get colder.",
  "Create an amazing memory. Plan it and write about it afterward.",
  "The year is nearly over, what are something you want to achieve before it ends?",
  "Make a Plan for the Christmas Holidays. Write about how the Holidays make you feel.",
  "What is your favorite winter activity?",
  "Did you reach your goals? Why? Why not?",
  "What is a skill you would like to learn next year?",
  "Write about going back to school after summer vacation.",
  "Write a thank you note to a friend who gave you onion and garlic-flavored chewing gum.",
  "Draw an imaginary constellation.  Write a story such as ancient people might have told about it.",
  "Describe a real made-up dream or nightmare. journal writing prompts",
  "Write about your favorite childhood toy. journal writing prompts",
  "Write out the best or the worst day of your life.  ",
  "Finish this thought: if I could change one thing about myself (if you can't think of anything, you might want to consider telling how you got to be perfect!)  ",
  "If and when I raise children, I'll never...  ",
  "I have never been more frightened than when...  ",
  "Persuade a friend to give up drugs. ",
  "Five years from now, I will be... journal writing prompts",
  "Write about a day you'd like to forget.  ",
  "Invent and describe a new food. journal writing prompts",
  "Describe an event that changed your life forever, or make up and describe an event that would change your life forever. ",
  "Describe someone who is a hero to you and explain why.",
  "Write about a time in your life when you struggled with a choice and made the right one.",
  "Imagine yourself in a different century and describe an average day in your life.",
  "Which character from a book would you most like to meet and why? journal writing prompts",
  "Three goals I have set for myself are...",
  "If you are given $5000, what will you do with that money?",
  "If you have to support a charity or a cause, which charity would you support? Why?",
  "What will you do if you win the lottery?",
  "What will you do if you are given the option to stay at home instead of going to school?",
  "Are you satisfied with your life right now?",
  "What would you like to change about your life?",
  "What is the best thing about your life?",
  "What is your biggest regret?",
  "What are you most grateful for in your life?",
  "What is your best childhood memory?",
  "What do you remember the most when you think of home?",
  "What is the best thing about growing up?",
  "When people think of you, how would they describe you?",
  "If there is anything you can do right now, what would you do?",
  "If money was not a problem, how would live your life?",
  "Is there anything you imagine a lot as a child?",
  "What do you always wish for?",
  "What are your goals for next year?",
  "What has the pandemic thought you?",
  "Are friends more important or family?",
  "If you could turn back time, to which moment would you like to go back too?",
  "If you had $5000 to spend on yourself, how would you spend it?",
  "If you could be anything you want to be without being judged, who would you be?",
  "Is there anything you wished you had learned when you were younger?",
  "What advice would you give to your younger self?",
  "Is there a new skill you would like to learn?",
  "What is your goal?",
  "Is there any book that you would also re-read?",
  "What is the best advice you have ever received?",
  "What is the first thing you notice when you meet someone new?",
  "What are you most thankful for in your life?",
  "What is the one thing you wish you can do at some point in your life?",
  "Create a bucket list of things you would like to achieve before the age of 50.",
  "Write a letter to yourself that you would open 5 years from now.",
  "What scares yours about dying?",
  "Do you think you are often misunderstood?",
  "If you can change one thing about the world, what would you change?",
  "Who is the biggest influencer in your life?",
  "Who do you admire the most in your life?",
  "Did you expect your life would be the way it is right now?",
  "“If I had the courage, I would…..”",
  "Do you think God really exist?",
  "Look at the room you sitting at right now, how does it make you feel?",
  "If you had $5000 to spend on yourself, how would you spend it?",
  "If you could be anything you want to be without being judged, who would you be?",
  "Is there anything you wished you had learned when you were younger?",
  "What advice would you give to your younger self?",
  "Is there a new skill you would like to learn?",
  "What is your goal?",
  "Is there any book that you would also re-read?",
  "What is the best advice you have ever received?",
  "What is the first thing you notice when you meet someone new?",
  "What are you most thankful for in your life?",
  "What is the one thing you wish you can do at some point in your life?",
  "Create a bucket list of things you would like to achieve before the age of 50.",
  "Write a letter to yourself that you would open 5 years from now.",
  "What scares yours about dying?",
  "Do you think you are often misunderstood?",
  "If you can change one thing about the world, what would you change?",
  "Who is the biggest influencer in your life?",
  "Who do you admire the most in your life?",
  "Did you expect your life would be the way it is right now?",
  "“If I had the courage, I would…..”",
  "Do you think God really exist?",
  "Look at the room you sitting at right now, how does it make you feel?",
  "What can I do to feel happier?",
  "What are the negative energy I should remove in my life?",
  "What is my biggest struggle?",
  "What negative thoughts do I need to stop saying to myself?",
  "What morning affirmations should I say to myself so I feel good every day?",
  "What should I do during the weekend so I can feel recharged for Monday?",
  "What new skill should I learn or acquire?",
  "What is stopping me from going after my dreams?",
  "What are the 3 words that describe me the most?",
  "Is there anything kind that I did recently?",
  "How can I support a local charity besides donating money?",
  "Is having more money going to make me happier?",
  "What does an ideal day look like?",
  "What are my top 3 goals for the rest of the year?",
  "How do I describe the friendship I have with my friends?",
  "How can I be kinder to myself?",
  "Am I being to hard on myself?",
  "What would I do if I knew I would never fail?",
  "write your eulogy",
  "What’s the highlight of your day so far?",
  "Imagine aliens landed on earth, what will they say to humans?",
  "Finish this sentence, the smell of an apple reminds me of….”",
  "You get 3 wishes fulfilled, what are your wishes?",
  "Write safety instructions for passengers traveling to the moon.",
  "Summarise your life story in less than 500 words",
  "You woke up one day and found yourself in the opposite sex, what happens next?",
  "You have been voted as the leader of your country, what is the first thing you would do?",
  "Pick a country you have never visited, why would you move there?",
  "You are responsible to deliver food to people living on mars but you forgot your way there, what did you do next?",
  "You work as a spy in North Korea, what did you discover?",
  "You woke up one day and found yourself as one of the characters in a video game, describe what happens next?",
  "What advice do you often give people but never follow it yourself?",
  "What is the best thing about high school?",
  "What would you like to change about your school?",
  "Which is your favorite subject in school?",
  "Who inspired you the most?",
  "How would you describe your friends in high school?",
  "What is the biggest lesson you ever learned in high school?",
  "What will you NOT miss about high school?",
  "How does it feel being a teenager?",
  "What is the best advice you have ever received?",
  "Did you stand up against a bully at school?",
  "What is your proudest moment at high school?",
  "What is your biggest achievement so far?",
  "What career line do you think is best for you?",
  "Write about someone you admire the most.",
  "What motivated you to work towards your goals?",
  "Who had the worst influence on you?",
  "Write about an experience you will never forget.",
  "Write about something you wish you had not done in high school.",
  "How do you imagine your life 10 years from now?",
  "What is the best thing about high school?",
  "What would you like to change about your school?",
  "Which is your favorite subject in school?",
  "Who inspired you the most?",
  "How would you describe your friends in high school?",
  "What is the biggest lesson you ever learned in high school?",
  "What will you NOT miss about high school?",
  "How does it feel being a teenager?",
  "What is the best advice you have ever received?",
  "Did you stand up against a bully at school?",
  "What is your proudest moment at high school?",
  "What is your biggest achievement so far?",
  "What career line do you think is best for you?",
  "Write about someone you admire the most.",
  "What motivated you to work towards your goals?",
  "Who had the worst influence on you?",
  "Write about an experience you will never forget.",
  "Write about something you wish you had not done in high school.",
  "How do you imagine your life 10 years from now?",
  "What did you say Yes to today?",
  "Did you try something new recently?",
  "What does your dream life look like?",
  "What is your biggest strength?",
  "What is your best childhood memory?",
  "What are your weaknesses?",
  "What can you do to make the week ahead of a good one?",
  "How far are you from reaching your goals?",
  "What did you laugh about recently?",
  "List 2 things you cherish the most?",
  "Do you have empathy towards other people?",
  "What are the things people like best about you?",
  "What do you feel most uncomfortable doing?",
  "What are the things you need to work on in your life?",
  "What aspects of your life need more attention right now?",
  "Write a letter to your future self.",
  "What will you do if you are not afraid to be judged?",
  "What are you excited about in the future?",
  "What will you like to work in for the next few weeks?",
  "Your favorite movie this month",
  "The best place you visited this month",
  "The best day of the month",
  "Something you let go of this month",
  "Something new you learn this month",
  "What are the things you look forward to next month?",
  "Some of the worst/best jokes you heard this month?",
  "What is your favourite music this month?",
  "The biggest news headline that happened this month,",
  "What are the goals accomplished this month?",
  "Did you fail at something this month?",
  "What held you back this month?",
  "Who helped you the most?",
  "7 random things you did this month.",
  "What are you most grateful for?",
  "Who is the last person you said sorry to this month?",
  "What is the best part of your month?",
  "What is your favourite thing about the month?",
  "Name 3 new things you tried this month?",
  "How did you relax?",
  "What motivated you?",
  "What is the one goal you achieved this month?",
  "What are you most proud of?",
  "What are the things you look forward to next month?",
  "What is the best thing that happened to you recently?",
  "Who/who made you feel special and loved?",
  "What is your favorite outdoor activity?",
  "Name 3 people you can rely on",
  "Name someone that was kind to you today",
  "Who are the people that will always make you smile?",
  "What do you like most about your current life and situation?",
  "Who do you do to unwind?",
  "Name 2 people you are grateful for in your life?",
  "What do you enjoy doing the most?",
  "Write things you like most about your family",
  "What are things you take granted for in your life?",
  "Name the people that would cheer you up when you are feeling down?",
  "What inspire you the most?",
  "What do you look forward to in your life?",
  "Write about something magical that happened to you recently",
  "Write about the best food you recently ate.",
  "Write about a book you enjoy reading.",
  "Write about something that keeps you nice and warm",
  "Write about a wish that came true",
  "Write about a teacher you are grateful for.",
  "Look around the room you are in right now, and write all the beautiful things you can see in it.",
  "What skills are you grateful for in your life?",
  "What do you think gratitude means?",
  "What are the things about this year you are thankful for?",
  "What are the two thing in your life you are thankful for?",
  "How do you practice gratitude on a daily basis?",
  "Write down new habits you would like to implement.",
  "When you look into the mirror, what do you see?",
  "Write about the moment you overcome something difficult by believing in yourself.",
  "Write down the emotions you are feeling right now as you are writing this.",
  "Review your goals in the last 1 year and see how far you have made it.",
  "Describe the happiest place on earth",
  "Places you enjoy visiting",
  "Dear past me…..",
  "Top 3 goals for the year",
  "Long term goals",
  "Dear future me….",
  "Skills you would like to learn this year…",
  "New hobbies you would like to try…",
  "3 ways you will make this year a good one….",
  "Ways in which you are amazing……",
  "Gifts you would like to receive from others….",
  "100 things you are grateful for…..",
  "Money-making ideas you would like to try…",
  "Things you would like to do with the family……",
  "Things you love about your close friends…",
  "Self-care practices you would like to try….",
  "New restaurants you would like to visit…",
  "Summer activities you would like to do this year…",
  "New Christmas celebration this year…..",
  "Movies you would like to watch….",
  "People you would like to thank….",
  "Adventures you want to try…..",
  "Experiences you would like to cherish…..",
  "Books you would like to read……",
  "3 things you love the most",
  "3 things you are grateful about",
  "3 celebrities you love",
  "3 favorite food",
  "3 favorite TV shows of all time",
  "3 music you listen when you are feeling down",
  "3 things you want from a relationship",
  "The best moment of your life",
  "The best thing you have ever done for someone else",
  "The best thing you did for yourself",
  "The best present you have ever received",
  "The best gift you have given to the world",
  "The best time of your life",
  "What would you do if you will never fail?",
  "What would you do if money was not an issue?",
  "What will you let go of in life?",
  "What is a perfect day for you?",
  "Close your eyes and imagine what the perfect world looks like to you?",
  "What is the craziest dream you ever had?",
  "What are top 3 things you wish you can have in your life?",
  "When do you feel the world stop?",
  "What is your personal motto?",
  "What is the greatest gift you ever received?",
  "Are you an impulsive person or someone who prefers to “wait and see”?",
  "Write about a leader who inspires you.",
  "What irrationally annoys you more than anything else?",
  "What small thing can always bring you a bit of joy?",
  "What is your favorite thing to do on a lazy day?",
  "How often do you take risks?",
  "Write about your happiest memory.",
  "What is your favorite thing about being male or female?",
  "Who is your favorite president? What do you admire about him?",
  "How long do you think it will be before we see a female president?",
  "Do you think it’s important to be a part of a community? Why or why not?",
  "Write a thank-you note to someone who has made a difference in your life.",
  "What piece of modern technology are you most grateful to have?",
  "What would your life today be like without the Internet?",
  "Do you feel anonymous online? Why or why not?",
  "Do you prefer to binge-watch TV or keep up week-to-week? Why or why not?",
  "Write about your writing habits and what they say about you.",
  "What is something you’ve always wanted to try but have never gotten around to?",
  "Can money buy happiness?",
  "Write about a time when you had a profound disagreement with a friend.",
  "If you could have a book with all the answers, would you read it? Why or why not?",
  "What goal are you working on right now?",
  "When do you feel most connected to other people?",
  "What is the greatest challenge you’ve ever faced?",
  "Writing Prompts for Daily Writing",
  "Write about a time when you couldn’t stop laughing.",
  "What is the most intense dream you’ve ever had?",
  "What is your favorite way to treat yourself after a long week?",
  "What thought scares you more than anything else? How do you cope with it?",
  "What are you exceptional at? Describe your talent.",
  "When do you feel most at peace?",
  "If you could create your own day of awareness, what would it be for?",
  "What would you put in a buried treasure chest?",
  "If you could rid the world of one problem, what would it be?",
  "What was the most exciting piece of news you ever received?",
  "Who knows you better than anyone else?",
  "How do you define success? Who is a successful person according to your definition?",
  "Are you the life of the party or someone who prefers to sit back and observe?",
  "Write about the last time you helped someone.",
  "What is the most interesting fact you know—and why does it interest you?",
  "Write about a time when you heard, read, or saw something that you weren’t supposed to. What happened?",
  "Have you ever fallen in love?",
  "Do you follow current events? Why or why not?",
  "What is the greatest benefit of journaling?",
  "If you could have any one question answered, what would it be? How would the answer impact your life?",
  "What is the earliest lesson you remember learning from your parents?",
  "Write about one thing from your childhood that you will always carry with you.",
  "How do you define “family”?",
  "Do you believe in ghosts or spirits? Why or why not?",
  "How frequently do you exercise or engage in physical activity? Are you satisfied with your habits? Why or why not?",
  "Write about an aspect of another culture that interests you and that you’d like to learn more about.",
  "Write about something you love that you think everyone else should try, too.",
  "Would you ever consider going to space? Why or why not?",
  "What is the most important thing you look for in a friend?",
  "What value do you hold most dear? Why?",
  "Choose three words to describe the current state of your life—and then explain why you chose them.",
  "Write about a time when you created something amazing.",
  "Would you rather be rich, successful, healthy, or famous? Why?",
  "What do you think one of the hardest jobs in the world is? Would you ever consider doing it?",
  "Write about a time when someone confided in you. How did their trust make you feel?",
  "Write about a time when you encountered a bully—and what you did to address the situation.",
  "Are you more scientific-minded or creative-minded? How does that affect your life?",
  "Write about a special memory that might not have looked so special to someone on the outside.",
  "What kind of impact do commercials and advertising have on your life?",
  "What do you spend most of your time doing? How do you feel about that?",
  "Write a 50-word description of yourself that you could give to someone you’d never met. How accurately does it describe you?",
  "Who inspires you? Why?",
  "What is something you are proud of?",
  "Write a letter to your high school self.",
  "What would you do if you knew you could not fail?",
  "What is your ideal life? How can you achieve it?",
  "What is going well in your life right now?",
  "Describe in detail what you want your life to be like 5 years from now.",
  "If you had a million dollars, what would you spend it on and why?",
  "Are you living to your full potential? If not, why?",
  "Are holding grudges? Write them down and let them go.",
  "What makes you feel the most confident?",
  "Write a thank you letter to your biggest supporter.",
  "What was your biggest learning moment this week?",
  "Write a thank you letter to your body.",
  "What do you wish more people knew about you and why?",
  "What was your most embarrassing moment and why?",
  "If you could change anything about yourself what would it be and why?",
  "Describe your biggest accomplishment and why it means so much to you.",
  "How would you describe yourself to a stranger?",
  "If you could achieve anything in your life what would it be?",
  "How can you best serve your tribe today?",
  "What are your favorite topics to blog about?",
  "Who do you want to serve?",
  "What was the best thing that happened last week?",
  "What milestones did you reach last week?",
  "How do you want people to feel when they first encounter your brand?",
  "What makes you feel most successful?",
  "What’s a challenge you struggled with last week?",
  "What do you want your legacy to be?",
  "Does your website look the way you want it to? ",
  "List 10 things you want to improve in your business.",
  "List 3 non-negotiable daily actions that will move you closer to your goals.",
  "If you could do anything you wanted to do today, what would it be?",
  "How can your struggles help your audience?",
  "What fear would you like to overcome? What steps can you take to start overcoming it?",
  "What would you do if you did not have any fears?",
  "What is holding you back from going after the life you want?",
  "What are 3 of the biggest lessons you’ve learned from having anxiety?",
  "What are three things you can do to enhance your mental well-being?",
  "Write about a difficult time in your life and how you overcame it.",
  "Get something off your chest. What is something you may be over-thinking?",
  "What are 10 things that always make you feel better, no matter what?",
  "What are the biggest lessons you’ve learned from having depression?",
  "If I didn’t have depression I would have never …",
  "Write down the lyrics to a song that makes you happy.",
  "Reply to your inner critic’s opinions about your actions and decisions.",
  "Are you taking time to care for yourself? Do you allow yourself time to relax and breathe? If the answer is no, what can you do to give yourself this time?",
  "Make a list of the compliments you’ve received from others.",
  "What areas of your life could be more organized? How can you accomplish this?",
  "What steps have you taken towards a goal of yours?",
  "What was one problem you had today, and what was your solution to this problem?",
  "Write out a list of the things that are causing you stress at the moment. Looking at them on paper may help you realize that you can do it all.",
  "What past challenge has turned out to be a blessing in disguise? Why?",
  "What are some things you can look forward to after this stress subsides?",
  "How do you usually handle stress? Are you using these strategies now?",
  "What’s the weather outside your window doing right now? If that’s not inspiring, what’s the weather like somewhere you wish you could be?",
  "How do you feel when you love someone who does not love you back?",
  "Talk about your feelings and how you feel about the day that you have planned. ",
  "Listen to the sounds around you and describe them. ",
  "What if … write the what if of your project to work through any obstacles. ",
  "List 3 things you plan to do today for your health.",
  "Write down your meal plan for the day.",
  "If you could be anywhere right now, write down where you would be and how it would make you feel. ",
  "Write about what your ideal day would look like.",
  "Note down a list of 12 things that make you smile.",
  "Know that game 2 truths and a lie, if you were playing that what would you share. ",
  "Describe a moment in your life that you will never forget. ",
  "Write a list of questions you have for your mentor.",
  "Admit some truths. The secret you’ve been keeping. ",
  "Write out a forgiveness note. The one thing you would like forgiveness for. ",
  "The most important day of my life is … ",
  "The most fun I’ve ever had was … ",
  "Just 10 things. 10 people I’d like to meet, 10 foods I’d like to try. 10 sports or fitness activities I’d like to try…",
  "If I was in a movie, I’d be in… and I’ll be … this is the plot…",
  "My favourite thing to do on a Monday is ….",
  "The holidays I like best are …",
  "This is a family tradition I love that I still do … ",
  "This is a family tradition I will start with my family …",
  "If I knew I couldn’t fail I would do this …",
  "If I was granted three wishes this is what I’d ask for …",
  "My core values are …",
  "This is what I like about myself …",
  "This is how I describe myself …",
  "This is how my family and friends see me …",
  "What did I read this week that inspired me …",
  "What podcast did I listen to this week that inspired me … how was I inspired … ",
  "What 3 things am I grateful for at this very moment?",
  "What are 3 things that opened my mind or changed my perspective of the world that I am grateful for?",
  "Who are the 3 people I’m currently grateful to have in my life?",
  "What 3 things about this time of year am I grateful for?",
  "What are 3 things about technology that I am grateful for?",
  "What are 3 things about difficult times that I am grateful for?",
  "What are 3 things about the country I live in that I am grateful for?",
  "If I had a magic wand I would wish for this … What stops me from taking steps forward to change my life. ",
  "Where do I see myself in 1 year from now …",
  "Where do I see myself in 5 years from now … how about 10 years from now …",
  "What would I tell my five year old self …",
  "Who do I need to forgive and why? ",
  "What is the best advice I’ve been given to date?",
  "What advice would I give myself? ",
  "What is the one thing that causes me to self sabotage? ",
  "If I could invite 5 people for dinner living or dead who would sit around the table dining with me. Why did I choose those people?",
  "If my life was a story and I was writing the final chapter what would this chapter say?",
  "Write about a song and a feeling it invoked in you. ",
  "Recall an important memory from your childhood and tell it from the perspective of someone else who was present.",
  "Write about an item you have that isn’t expensive but means a lot to you.",
  "What color do you feel like today and why?",
  "Describe your favorite room in your home or apartment.",
  "What is the most adventurous thing you’ve eaten?",
  "Write a review of the last movie you saw. ",
  "Write about an imagined ideal day walking around a city of your choosing. ",
  "If you could live inside one of your favorite stories, what would you change about it?",
  "Write about why you want to write. ",
  "Write about something nice a stranger did for you.",
  "Describe your favorite piece of furniture in your childhood home.",
  "What was the last piece of media you read, heard, or saw that inspired you? ",
  "What is a dream you’ve had that you want to live in forever?",
  "Write about what you think the world will look like in 10 years.",
  "Describe what you imagine to be happening in a historical photograph.",
  "Write about a time you witnessed community solidarity. ",
  "Read the last postcard, letter, or personal email you received, and start a story with the first sentence.",
  "Who is the most interesting person you can think of? Create a list of questions you would ask them in an interview.",
  "Recall an object you found on the sidewalk/side of the road. Why did someone give it away? Why did they have it to begin with?",
  "Who is one person that you look up to and why?",
  "What is your favorite memory? Write down as many details as you can remember.",
  "What is one thing about today that surprised you?",
  "What is one mistake you made today and what did you learn from it?",
  "What are three things you’re grateful for?",
  "If you could spend one day doing anything you want, what would you do?",
  "What is one thing that helps you when you’re worried?",
  "If you could have any pet (even a magical creature like a dragon or unicorn), what would you want? What name would you give it?",
  "What’s one goal or challenge you have for yourself this week? How will you accomplish it?",
  "Think about your favorite hobby or activity. Why do you love it?",
  "What’s one thing that always makes you laugh?",
  "Close your eyes and listen to the world around you. What sounds do you hear? Write them down.",
  "Have you ever wanted to learn another language? What would you want to learn?",
  "What is the strangest thing you’ve ever learned in school?",
  "Write about your favorite holiday. Why is it your favorite? What’s your happiest memory associated with it?",
  "Would you rather it always be summer, spring, fall, or winter? Why?",
  "If you could tell your family one thing that’s been on your mind lately, what would you say?",
  "Do you have any pets? What would you say to it if, one morning, it could suddenly talk?",
  "What’s your favorite thing to do when you’re outside?",
  "Think about one person who makes you feel loved. How do they show you that they care?",
  "Have you been on a vacation? Where did you go, and what was your favorite part?",
  "Pretend that you had a time machine and could travel way into the future or to the past. Where would you go? What do you think life would be like?",
  "Do you have a favorite teacher? What are they like, and what’s the best thing they’ve taught you?",
  "What’s the funniest knock-knock joke you can think of?",
  "Write about one accomplishment you’ve reached that you’re proud of.",
  "What is one interesting fact that you learned today?",
  "What do you think would be the coolest job to have? Why?",
  "Think about one of your friends or a family member. What do you admire about them?",
  "Look out of your window. What do you see?",
  "Do you have a favorite book? Why is it your favorite?",
  "What do you want your life to be like when you’re grown up?",
  "When you get mad or grumpy, what’s one thing that helps you calm down?",
  "What’s the best advice someone has ever given you?",
  "What would you do if you were the main character in your favorite fairy tale?",
  "What is your favorite thing about yourself? What’s one thing you want to work on?",
  "What is one of your funniest memories? Write a poem about it.",
  "Think about your favorite color. What does it remind you of?",
  "Who is someone you miss? What would you say to them if they were next to you right now?",
  "What’s one thing you’ve never told anyone before?",
  "Do you have a favorite quote? Write it down here. Why is it your favorite?",
  "If you could be one of the first astronauts to go to Mars, would you? Why?",
  "What do you love about your family?",
  "Do you remember your first day of school? What was it like?",
  "If you could talk to your future self, what would you ask?",
  "If you could talk to your past self, what would you say?",
  "What is one thing you’re excited about? Why?",
  "If you could have any superpower, which one would you choose? What would you do with it?",
  "Write down one way you’ll make the most of today.",
  "What’s the best way to spend a rainy day?",
  "Pretend that you could either shrink down to the size of a mouse or grow as large as a building. What would you do and why?",
  "Write down three ways you could help a friend or family member today.",
  "Think about a talent you wish that you had. What’s one way that you can start practicing it?",
  "What do I know to be true that I didn’t know a year ago?",
  "What distractions get in the way of being my most productive?",
  "When do I feel most in tune with myself?",
  "If someone described me, what would they say?",
  "What can wait until next week?",
  "How does every part of my body feel in this moment?",
  "What emotions am I holding on to?",
  "How can I detach or neutralize this emotion?",
  "Why am I doing X?",
  "Why am I feeling this way?",
  "What is causing these feelings?",
  "Have I tried to take my ego out of the situation?",
  "How can I detach my emotions from the behavior of others?",
  "Did I use healthy boundaries before I began feeling this way?",
  "What hurts right now? How can I find relief?",
  "When I look in the mirror, what do I see?",
  "What are the things in my home that are the most “me”?",
  "What am I doing right now?",
  "What happened before I felt a shift in my mood?",
  "Write down an entire list of what you are worried about. Star the items that you know are 100% true and not solely a feeling.",
  "Write a list of 5 things you love about yourself, and why they make you unique.",
  "If you could be the best in the world at one thing, what would you choose and why?",
  "When you were little what did you want to be when you grew up, and did you follow through with your dream?",
  "What quote inspires you on tough days?",
  "If you could live anywhere in the world, where would you choose and why?",
  "If you won $1 million, what would you do with the money?",
  "What’s the best advice you’ve ever been given?",
  "If you could have lunch with one person who is no longer here with us, who would you choose and what one question would you ask them?",
  "What’s the biggest life lesson you’ve ever learned and how has it changed you?",
  "Describe a situation in your life that caused you to feel regret. If you could go back in time, what would you do differently?",
  "Write about a book/movie that had a big impact on your life, and why it affected you so much.",
  "What 3 things do you want the people you love the most to remember about you after you’re gone?",
  "Fill in the blank: When I’m feeling anxious or stressed, I ___________.",
  "Describe something GOOD that happened to you today.",
  "What’s the most embarrassing thing that’s ever happened to you?",
  "What scares you?",
  "Discuss a time you failed at something important to you. If you could have a do-over, what would you change about the situation?",
  "What are you most grateful for in your life?",
  "Pick ONE positive word you’d like to focus on this week and brainstorm a list of things you can do to experience this feeling each day.",
  "Describe your favorite time of year. What do you love about it, who do you spend it with, and what activities do you enjoy during that time?",
  "Write a letter to someone who has done you wrong. Discuss what they did and how it made you feel, and then forgive them and let it go.",
  "If you had $1,000 to spend on nobody but yourself, what would you buy and why?",
  "If you could change one thing about yourself, what would it be and why?",
  "What is your favorite childhood memory?",
  "Describe your perfect day.",
  "What qualities are important to you in a friendship/romantic relationship?",
  "List and describe the most important people in your life, and what you admire most about them.",
  "If you had one full day to yourself without any responsibilities, who would you choose to spend it with and what would you do?",
  "Discuss 3 things you’d like to change in your life, and brainstorm strategies to make these changes a reality.",
  "Describe your dream job.",
  "What 3 things do you love most about yourself, and why?",
  "Write a letter to your teenage self telling her all the things you wish she knew.",
  "Make a list of things that are holding you back from your wants, needs, goals, and desires. Be brutally honest with yourself, and brainstorm ways to overcome these obstacles.",
  "If you could travel to any destination in the world, where would you go and why?",
  "Describe a situation in which you helped someone else. What did you do? How did it make them feel? How did it make you feel?",
  "How would you describe yourself to a stranger?",
  "If you could change anything about yourself, what would it be and why?",
  "What are your top 5 values in life?",
  "What does self-care mean to you, and how can you incorporate it into your daily routine?",
  "Describe a time in your life when you failed. What did you learn from it?",
  "What are your best character traits?",
  "What is something nobody knows about you? Why have you kept it a secret?",
  "What does your ideal life look like?",
  "Write about an important person in your life who you are grateful for. What do you admire about this person, why have they had such an impact on your life, and what would you like to tell them?",
  "What is your biggest fear, and what about it makes you feel scared?",
  "What makes you feel fulfilled?",
  "If you could spend an entire day with one person, who would you choose to spend it with and what would you do together?",
  "When something good or bad happens, who is the first person you want to tell, and why?",
  "Discuss 5 things you wish others knew about you.",
  "What is your biggest regret in life, and if you could go back in time, what would you change about the situation?",
  "What quote or saying inspires you when you need it most?",
  "Look at yourself in the mirror and then write out 3-5 physical traits you love about yourself, and why.",
  "What do you want people to remember most about you when you’re gone?",
  "What inspires you?",
  "Who is your mentor, why do you look up to him/her, and what has he/she taught you?",
  "What is your 5-year plan? Map out all of the things you need to do to reach your goals.",
  "Do you have any unhealthy habits that are holding you back from your goals? How can you overcome them?",
  "What is the biggest life lesson you’ve learned to date? Describe how the lesson was learned, and how it has impacted your life.",
  "What is the best piece of advice you’ve ever been given, and why did it have such an impact on you?",
  "Create a bucket list of things you’d like to accomplish or experience in the next 12 months.",
  "Discuss 3 things you do well as a mom.",
  "What is your favorite time of day with your children?",
  "If you could have an entire day to yourself with no responsibilities, who would you want to spend the day with and what would you choose to do together?",
  "What is the best parenting advice you’ve ever received?",
  "What shocked you most about motherhood?",
  "What parts of motherhood do you find the most fulfilling?",
  "What is your most challenging time of day with your kids? Brainstorm 3-5 strategies you can start TODAY to make this time easier.",
  "Write a bucket list of things you’d like to experience with your children over the next 12 months, and schedule them into your calendar to keep yourself accountable.",
  "What qualities do you look for in a ‘mom friend’?",
  "Describe your biggest achievement as a mom. How did it make you feel?",
  "When your kids look back on their childhood, what 3 things do you hope they remember most?",
  "What’s the silliest thing your child has ever done/said?",
  "What scares you most about being a mom?",
  "Write a letter to your pre-mom self telling her all the things you wish she knew.",
  "How has your mom shaped you as a mother?",
  "What are your favorite family traditions?",
  "Discuss a time you felt you failed a mother. If you could have a do-over, what would you change about the situation?",
  "What makes you feel fulfilled?",
  "Describe 5+ things about your child(ren) that make you proud.",
  "Write about your experience with childbirth and how it changed you.",
  "How has your relationship with your spouse changed since you became a mom?",
  "What are your least favorite parts about being a mom, and how can you improve them?",
  "What does self-care mean to you now that you’re a mom?",
  "What do you wish other people understood about your specific experiences with motherhood?",
  "Write a letter to your children to open on their 18th birthday.",
  "What parts of motherhood are you most grateful for?",
  "How have your priorities changed since you became a mom?",
  "What parts of motherhood do you take for granted?",
  "Is there anything you miss about your pre-mom life?",
  "If you could change ONE thing about yourself as a mom, what would you change and why?",
  "Write about things you need to forgive yourself for.",
  "Write a letter of forgiveness to someone.",
  "If you had five other lives to lead, what would you do in each of them?",
  "What would you do if you could travel into the past?",
  "If you could change one thing about the world, what would it be?",
  "Write about the things that have changed your life.",
  "What is the most valuable thing you have learned from this life?",
  "Write down reasons you have faith in yourself.",
  "What does your happiest version look like to you?",
  "What do you do when people are negative and don’t support you?",
  "Write a letter to your anxious thoughts.",
  "How do you know when to let go?",
  "Your favorite quote that reminds you of your goals and dreams.",
  "Where do you see yourself in 5 years?",
  "What do you aspire to be?",
  "What does success mean to you?",
  "What is holding you back from living your dream life and accomplishing a goal?",
  "What are your top 3 goals for the month?",
  "Who has inspired creativity in you?",
  "What were you inspired to create as a child?",
  "What are your creative strengths?",
  "How has creativity helped you?",
  "How does it feel to create something of your own?",
  "List ten things you enjoy doing? When was the last time you let yourself do these things?",
  "Write a letter to your inner critic.",
  "What advice would you give to someone who want to lead a creative life?",
  "If you could create something for the rest of your life, what would that be?",
  "What was the feeling when you first discovered art?",
  "What are you trying to say with your art?",
  "Is art your life or part of your life?",
  "When do you feel the most accomplished as an artist?",
  "Write an encouraging letter to your inner artist?",
  "What’s going on inside you at this moment?",
  "On a scale of 1-10, how peaceful are you today?",
  "How do you stay present in everyday life?",
  "How do you feel at the moment?",
  "How is your heart today?",
  "What kind of person do you want to be?",
  "What are the things that keep you going?",
  "How do you find opportunities for growth in the midst of your present struggles?",
  "What are the things that you have given up on your road to becoming your best self?",
  "Old you vs. new you.",
  "What would your younger self be proud of you for today?",
  "Write about your can s , should s, and will s.",
  "Write about your can’t s, shouldn’t s, and wouldn’t s",
  "Write a letter to your chronic pain.",
  "Describe your illness.",
  "Lessons you learned from your illness.",
  "Which things have changed in your life after becoming ill? How do you manage to deal with these changes?",
  "What was your diagnosis journey like?",
  "What did your illness teach you about adaptability?",
  "How did the world around you change after you became ill?",
  "How do you maintain a balance in mind and body?",
  "How do you let go of the thought ‘why me’?",
  "Do you still feel compassion for others?",
  "How do you cope with loneliness and bad days?",
  "What keeps you grounded?",
  "What freedoms are you most grateful for?",
  "Describe your happiest memory.",
  "How is your life more positive today than it was a year ago?",
  "What makes you happy to be alive?",
  "List the treasures around you in your life.",
  "What’s an accomplishment you’re proud of?",
  "What’s one of your personality traits that you’re grateful for?",
  "What do you love most about life?",
  "Write about a moment in your life that was pure joy and light.",
  "What do you love about yourself?",
  "What makes you unique?",
  "Write a thank you letter to yourself.",
  "How do you show love to yourself on a daily basis?",
  "What is the biggest miracle of your life?",
  "Are you in the right path? If not, why not?",
  "Are you a truth seeker?",
  "What kind of world you want to live in?",
  "What does it mean to be free and fulfilled?",
  "Are you satisfied and content with your life?",
  "Why do most of us try to escape from the present moment?",
  "What do you think about enlightenment.",
  "What is the key to the inner peace?",
  "Write a letter to your subconscious mind.",
  "What do you think your spiritual gifts are?",
  "Word of the year is.",
  "One thing you learned last year.",
  "One habit that you gave up last year.",
  "Quote that inspired you last year.",
  "A letter to the past year.",
  "Your photo album of last year looked like.",
  "In what three ways have you made last year memorable?",
  "What did you do for yourself last year?",
  "What were you most thankful for last year?",
  "Did you attained all the goals of last year? What are your goals for this year?",
  "Are you the same person you were at the beginning of last year?"
  "Dear Future Me,",
  "Dear Past Me,",
  "Happiness is…",
  "I find it so beautiful that…",
  "I’m getting in the way of my goals by…",
  "If money weren't a concern...",
  "I find it difficult to tolerate...",
  "A memory that makes me smile...",
  "My job makes me feel...",
  "Success is...",
  "Love is...",
  "I feel most like myself when…",
  "If I weren't afraid of getting rejected or looking foolish, I would ...",
  "I feel confident when...",
  "(Think about a recent setback. What did you learn from the experience?)",
  "One thing that makes me feel grounded in times of uncertainty...",
  "A blessing in disguise has been...",
  "I have a weakness for...",
  "If I could change something about the way I was raised...",
  "I’m proud of...",
  "I miss...",
  "My deepest desire...",
  "I want to be better at...",
  "My biggest source of fear, anxiety, or distress...",
  "My favorite quality in others...",
  "If I die tomorrow, I will most regret not having done...",
  "Even though it was hard, I'm glad I...",
  "A positive change in myself I have experienced in the past year...",
  "I’m lucky because...",
  "(There's a saying; ‘If it doesn't matter in 10 years, it doesn't matter now’) what's one thing that seems to matter now but won't in 10 years?",
  "If I had one year left to live, I would...",
  "I believe in...",
  "I feel vulnerable when...",
  "My five-year-old self would be proud of the person I am today because...",
  "My five-year-old self would be sad or disappointed in the person I am today because...",
  "I forgive...",
  "If I'm being honest with myself, I dislike...",
  "My top five values are...",
  "The world is...",
  "Currently, my work-life balance...",
  "I’m lucky to have a friend like...",
  "As I get older, I realize...",
  "My current (1) exercise regimen, (2) diet, and (3) sleep schedule...",
  "(Make a list of things that make you smile.)",
  "I think I'm holding onto hurt or anger from...",
  "I show love by...",
  "If I knew I could not fail. I would...",
  "The most meaningful experience of my life...",
  "I feel supported when...",
  "The most important person in my life is...",
  "I feel alive when...",
  "I want to learn more about...",
  "An act of kindness I'Il never forget...",
  "I’m inspired by...",
  "I feel satisfied and content when...",
  "(Think of a time you wronged someone or acted in a way that went against your values. Write an apology.)",
  "When I look at my finances, I feel...",
  "Intimacy is...",
  "A flaw I want to work on...",
  "(Think for a moment and answer: How does it feel to be you?)",
  "I’m grateful that my body...",
  "My 'happy place' looks like...",
  "When I die, I want to leave behind...",
  "I forgive myself for...",
  "It makes me angry when...",
  "If I could give one piece of advice to a teenager, it would be...",
  "I would like...",
  "(Think of a challenge in your life. If you had to imagine a reason for it being there, what would it be? What's one possible silver lining?)",
  "A lesson I had to learn the hard way...",
  "I was brave for...",
  "I feel most afraid when...",
  "I trust...",
  "I take responsibility for...",
  "(You are a gift this world has never seen, and will never see again. What is one quality about you that makes you feel unique?)",
  "In my career, I want to accomplish...",
  "I want to overcome...",
  "I’m afraid of wanting...",
  "I feel insecure about...",
  "My idea of the perfect day consists of...",
  "(Write about the last time you remember crying.)",
  "(Write about the last time you remember laughing.)",
  "(Describe the kind of partner that would be good for you.)",
  "I feel most like myself when...",
  "The most important thing in my life right now...",
  "A person or experience that has made me the person I am today...",
  "I believe my calling is...",
  "Femininity is...",
  "Masculinity is...",
  "Something I've always wanted but never had...",
  "Strength is...",
  "I misjudged...",
  "I wish others knew...",
  "I feel drained when...",
  "I want to try...",
  "One thing I like about myself is...",
  "I feel a sense of belonging when...",
  "I don't spend enough time with...",
  "I’m grateful for...",
  "I think my closest friends would describe me as...",
  "All that really matters in the end...",
  "I want to forgive...",
  "I am not willing to sacrifice...",
  "I feel the most present when...",
  "My favorite quality about myself is...",
  "If my body could talk, it would tell me...",
  "Something I learned in the past month...",
  "I wish I never stopped...",
  "A saying or principle l'd like to live by...",
  "A 'good friend' is someone who...",
  "I long for the freedom to...",
  "Right now, my overall state of health (physical, mental, emotional, etc.) is...",
  "My special power is...",
  "A goal that is worthy of my time and commitment is…",
  "(Think of the person to whom you most want to tell 'I love you.' Write a little note to that person.)",
  "(Think of a challenge you're facing. Now imagine yourself at 90, looking back with 20/20 hindsight. What would she say?",
  "My hero is...",
  "In five years, I want to have...",
  "I can't imagine living without...",
  "I feel energized when...",
  "(Fast forward 10 years into the future. Write a letter to your current self from the vantage point of your future self.)",
  "My relationship with the divine, God, the universe...",
  "If I were really honest with myself...",
  "Something new I recently a tried...",
  "My relationship with my parents...",
  "A recent change has been...",
  "I feel guilty or ashamed about...",
  "The most notable thing that has happened recently...",
  "A habit or skill I want to acquire is...",
  "Despite the consequences, I'm NOT sorry l...",
  "I practice self-love by...",
  "I want to stop...",
  "A ‘bucket list’ item I want to have done by the time I turn 21 is...",
  "A life-changing moment...",
  "I dare myself to...",
  "I’m aware of being influenced by...",
  "(Write 3 things you want to accomplish in 3 years, and smaller steps you can immediately take for each goal.)",
  "My ideal social life...",
  "I’m beginning to change my opinion on...",
  "(Imagine a life that's genuinely enjoyable and productive. What would you be doing? Where? With whom? How?)",
  "I can cut myself some slack when it comes to...",
  "I can expect more from myself when it comes to...",
  "I’ll never grow tired of...",
  "If today were my last day on earth...",
  "I would like to be able to...",
  "I’m excited for...",
  "(Think of someone you dislike. What's one thing you can learn from them?)",
  "(Think of someone you admire. What makes them admirable?)",
  "I feel like a badass when...",
  "Something I learned in the past year...",
  "I should spend less time on...",
  "(Imagine lying on your death bed, finishing the sentence ‘I wish I got to…’ what are the first five things that come to mind?)",
  "I love my partner because...",
  "1 thing I appreciate my partner for is...",
  "My relationship with my siblings...",
  "I can improve my relationship with my family by...",
  "My grade school years...",
  "My middle school years...",
  "My high school years...",
  "My college years...",
  "(Imagine your ideal future...Describe it in detail.)",
  "(Imagine a future you'd like to stay away from...Describe it in detail.)",
 ]
